"""empty message

Revision ID: a48dc4edf1fd
Revises: 65eae924b142
Create Date: 2020-06-10 04:26:24.070565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48dc4edf1fd'
down_revision = '65eae924b142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('screen_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('embedding', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tweet', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('tweet', sa.Column('name', sa.String(length=128), nullable=True))
    op.drop_column('tweet', 'user_id')
    op.drop_column('tweet', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('user_name', sa.VARCHAR(length=128), nullable=True))
    op.add_column('tweet', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.drop_column('tweet', 'name')
    op.drop_column('tweet', 'id')
    op.drop_table('tweets')
    op.drop_table('user')
    # ### end Alembic commands ###
